name: 🧪 WinTuner proxy
on:
  workflow_dispatch:
  schedule:
    - cron: '28 7 * * 1,4,6'

jobs:
  proxy:
    permissions:
      checks: write
    name: ✅ Check proxy
    runs-on: ubuntu-latest
    steps:
      - name: 👨‍💻 Check-out code
        uses: actions/checkout@v4

      - name: 📦 Install Pester
        shell: pwsh
        run: Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser

      - name: 🧪 Run test
        shell: pwsh
        run: |
          Import-Module Pester
          $pesterConfig = [PesterConfiguration]@{
            Output = @{
              Verbosity = "Detailed"
              CIFormat = "GithubActions"
              StackTraceVerbosity = "FirstLine"
            }
            TestResult = @{
              Enabled = $true
              OutputPath = "${{ github.workspace }}/testresults/TestResults.xml"
              OutputFormat = "JUnitXml"
            }
            Run = @{
              Path = "./tests/WinTuner.Proxy.Tests"
              Exit = $true
            }
            Should = @{
              ErrorAction = "Continue"
            }
          }
          Invoke-Pester -Configuration $pesterConfig
        env:
          WINTUNER_PROXY_CODE: ${{ secrets.WINTUNER_PROXY_TOKEN }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ${{ github.workspace }}/testresults/*.xml
          check_run: false
          job_summary: true
          compare_to_earlier_commit: false
